services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marline
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marline_test
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
