/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    clinics: Clinic;
    hospitals: Hospital;
    doctors: Doctor;
    'doctor-clinic-sessions': DoctorClinicSession;
    specialities: Speciality;
    services: Service;
    articles: Article;
    testimonials: Testimonial;
    faqs: Faq;
    'hospital-doctors': HospitalDoctor;
    'hospital-specialities': HospitalSpeciality;
    'hospital-testimonials': HospitalTestimonial;
    'gallery-images': GalleryImage;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clinics: ClinicsSelect<false> | ClinicsSelect<true>;
    hospitals: HospitalsSelect<false> | HospitalsSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    'doctor-clinic-sessions': DoctorClinicSessionsSelect<false> | DoctorClinicSessionsSelect<true>;
    specialities: SpecialitiesSelect<false> | SpecialitiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'hospital-doctors': HospitalDoctorsSelect<false> | HospitalDoctorsSelect<true>;
    'hospital-specialities': HospitalSpecialitiesSelect<false> | HospitalSpecialitiesSelect<true>;
    'hospital-testimonials': HospitalTestimonialsSelect<false> | HospitalTestimonialsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Isolation root for clinic and hospital microsites. Create tenants here first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL segment, e.g. aspire-childrens or synapse-neuro-center
   */
  slug: string;
  type: 'clinic' | 'hospital';
  status: 'active' | 'inactive';
  /**
   * Optional custom domain for future host-based routing
   */
  domain?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super admins see all tenants. Admins only see assigned tenants.
   */
  role: 'super_admin' | 'admin';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  /**
   * Original remote URL used for Drupal/import deduplication
   */
  sourceUrl?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics".
 */
export interface Clinic {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Drupal taxonomy_term--clinic UUID
   */
  drupalUuid?: string | null;
  /**
   * Drupal internal tid
   */
  drupalTid?: number | null;
  name: string;
  /**
   * e.g. synapse-neuro-center
   */
  slug: string;
  /**
   * Controls which page layout renders this clinic.
   */
  template: 'classic-teal' | 'minimal';
  description?: string | null;
  /**
   * Clinic phone / SMS number
   */
  phone: string;
  email?: string | null;
  instructions?: string | null;
  /**
   * Drupal field_clinic_location (e.g. Jayanagar-Synapse Neuro Center)
   */
  locationLabel?: string | null;
  /**
   * Clinic Open Close Text
   */
  openCloseText?: string | null;
  rating?: number | null;
  reviewCount?: number | null;
  priceRange?: string | null;
  areaServed?: string | null;
  /**
   * Drupal field_color_code_clinic
   */
  colorCode?: string | null;
  showBlogs?: boolean | null;
  showTestimonials?: boolean | null;
  specialities?: (number | Speciality)[] | null;
  services?: (number | Service)[] | null;
  /**
   * Clinic Logo (not the hero banner)
   */
  logo?: (number | null) | Media;
  banners?: {
    /**
     * Large desktop banner (landing hero)
     */
    desktopBanner?: (number | null) | Media;
    /**
     * Mobile banner image
     */
    mobileBanner?: (number | null) | Media;
  };
  address: {
    line1: string;
    /**
     * Parsed from Drupal free-text address when missing
     */
    city: string;
    state: string;
    postalCode: string;
    latitude: number;
    longitude: number;
  };
  /**
   * Raw Google Maps iframe HTML from Drupal
   */
  mapHtml?: string | null;
  workingHours?:
    | {
        /**
         * Doctor label / reference from Drupal "To Doctor"
         */
        toDoctor?: string | null;
        clinicDays?: string | null;
        clinicHours?: string | null;
        mobileNumber?: string | null;
        instructions?: string | null;
        /**
         * Priority rules for voice AI
         */
        priorityRule?: string | null;
        specialtyKeyword?: string | null;
        ageGroup?: string | null;
        priorityLevel?: string | null;
        priorityScore?: number | null;
        /**
         * RFA / receptionist appointment number
         */
        appointmentClinicNumber?: string | null;
        id?: string | null;
      }[]
    | null;
  specialitiesSection?: {
    mainTitle?: string | null;
    subMainTitle?: string | null;
    items?:
      | {
          title?: string | null;
          shortDescription?: string | null;
          logo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  servicesSection?: {
    mainTitle?: string | null;
    items?:
      | {
          title?: string | null;
          logo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  youtubeVideos?:
    | {
        embedUrl?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKeywords?: string | null;
    /**
     * Drupal SEO meta → crawling Disable
     */
    crawlingDisabled?: boolean | null;
  };
  whatsapp?: {
    /**
     * Whatsapp middleware token
     */
    middlewareToken?: string | null;
    /**
     * Whatsapp token ID
     */
    tokenId?: string | null;
  };
  clinicSamAi?: {
    /**
     * Drupal field_clinic_sam_ai
     */
    enabled?: boolean | null;
  };
  symptomCollector?: {
    toDoctor?: string | null;
    /**
     * Symptom collector video (mp4)
     */
    video?: (number | null) | Media;
    botLanguages?:
      | (
          | 'en'
          | 'hi'
          | 'kn'
          | 'te'
          | 'ta'
          | 'ur'
          | 'am'
          | 'ar'
          | 'as'
          | 'bn'
          | 'dv'
          | 'fr'
          | 'gu'
          | 'kok'
          | 'ml'
          | 'mr'
          | 'ne'
          | 'pcm'
          | 'or'
          | 'si'
          | 'es'
          | 'sw'
        )[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialities".
 */
export interface Speciality {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  icon: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals".
 */
export interface Hospital {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Must match the parent tenant slug
   */
  slug: string;
  /**
   * Hospital tagline or slogan
   */
  tagline?: string | null;
  template: 'aspire-style' | 'modern-clinical' | 'minimal';
  /**
   * Main hero banner image
   */
  heroImage?: (number | null) | Media;
  phone: string;
  whatsappNumber?: string | null;
  /**
   * Slug for linqmd.com/hospital/{slug} booking link
   */
  linqmdBookingSlug: string;
  address: {
    line1: string;
    city: string;
    state: string;
    postalCode: string;
    latitude: number;
    longitude: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  photo: number | Media;
  tagline?: string | null;
  experienceYears?: number | null;
  stats?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  specialities?: (number | Speciality)[] | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-clinic-sessions".
 */
export interface DoctorClinicSession {
  id: number;
  tenant?: (number | null) | Tenant;
  doctor: number | Doctor;
  clinic: number | Clinic;
  /**
   * Minutes per consultation at this clinic
   */
  consultationDuration: number;
  availableDays: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[];
  /**
   * Dates blocked for THIS doctor at THIS clinic only
   */
  blockedDates?:
    | {
        date: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  coverImage: number | Media;
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  clinic: number | Clinic;
  publishedDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  patientName: string;
  review: string;
  clinic: number | Clinic;
  doctor?: (number | null) | Doctor;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  tenant?: (number | null) | Tenant;
  question: string;
  answer: string;
  clinic: number | Clinic;
  doctor?: (number | null) | Doctor;
  verifiedPatient?: boolean | null;
  visitReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-doctors".
 */
export interface HospitalDoctor {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  designation?: string | null;
  speciality?: string | null;
  experience?: string | null;
  qualification?: string | null;
  image?: (number | null) | Media;
  description?: string | null;
  /**
   * Languages spoken (comma-separated)
   */
  languages?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-specialities".
 */
export interface HospitalSpeciality {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  description?: string | null;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-testimonials".
 */
export interface HospitalTestimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  patientName: string;
  rating?: number | null;
  testimonial: string;
  date?: string | null;
  treatment?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  image: number | Media;
  category?: ('facilities' | 'events' | 'awards' | 'team' | 'other') | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL-friendly slug for the blog post
   */
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author?: string | null;
  publishedDate?: string | null;
  category?: string | null;
  /**
   * Tags (comma-separated)
   */
  tags?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clinics';
        value: number | Clinic;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: number | Hospital;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'doctor-clinic-sessions';
        value: number | DoctorClinicSession;
      } | null)
    | ({
        relationTo: 'specialities';
        value: number | Speciality;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'hospital-doctors';
        value: number | HospitalDoctor;
      } | null)
    | ({
        relationTo: 'hospital-specialities';
        value: number | HospitalSpeciality;
      } | null)
    | ({
        relationTo: 'hospital-testimonials';
        value: number | HospitalTestimonial;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  status?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  sourceUrl?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics_select".
 */
export interface ClinicsSelect<T extends boolean = true> {
  tenant?: T;
  drupalUuid?: T;
  drupalTid?: T;
  name?: T;
  slug?: T;
  template?: T;
  description?: T;
  phone?: T;
  email?: T;
  instructions?: T;
  locationLabel?: T;
  openCloseText?: T;
  rating?: T;
  reviewCount?: T;
  priceRange?: T;
  areaServed?: T;
  colorCode?: T;
  showBlogs?: T;
  showTestimonials?: T;
  specialities?: T;
  services?: T;
  logo?: T;
  banners?:
    | T
    | {
        desktopBanner?: T;
        mobileBanner?: T;
      };
  address?:
    | T
    | {
        line1?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  mapHtml?: T;
  workingHours?:
    | T
    | {
        toDoctor?: T;
        clinicDays?: T;
        clinicHours?: T;
        mobileNumber?: T;
        instructions?: T;
        priorityRule?: T;
        specialtyKeyword?: T;
        ageGroup?: T;
        priorityLevel?: T;
        priorityScore?: T;
        appointmentClinicNumber?: T;
        id?: T;
      };
  specialitiesSection?:
    | T
    | {
        mainTitle?: T;
        subMainTitle?: T;
        items?:
          | T
          | {
              title?: T;
              shortDescription?: T;
              logo?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        mainTitle?: T;
        items?:
          | T
          | {
              title?: T;
              logo?: T;
              id?: T;
            };
      };
  youtubeVideos?:
    | T
    | {
        embedUrl?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        crawlingDisabled?: T;
      };
  whatsapp?:
    | T
    | {
        middlewareToken?: T;
        tokenId?: T;
      };
  clinicSamAi?:
    | T
    | {
        enabled?: T;
      };
  symptomCollector?:
    | T
    | {
        toDoctor?: T;
        video?: T;
        botLanguages?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals_select".
 */
export interface HospitalsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  tagline?: T;
  template?: T;
  heroImage?: T;
  phone?: T;
  whatsappNumber?: T;
  linqmdBookingSlug?: T;
  address?:
    | T
    | {
        line1?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  photo?: T;
  tagline?: T;
  experienceYears?: T;
  stats?:
    | T
    | {
        label?: T;
        id?: T;
      };
  specialities?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-clinic-sessions_select".
 */
export interface DoctorClinicSessionsSelect<T extends boolean = true> {
  tenant?: T;
  doctor?: T;
  clinic?: T;
  consultationDuration?: T;
  availableDays?: T;
  blockedDates?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialities_select".
 */
export interface SpecialitiesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  clinic?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  patientName?: T;
  review?: T;
  clinic?: T;
  doctor?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  tenant?: T;
  question?: T;
  answer?: T;
  clinic?: T;
  doctor?: T;
  verifiedPatient?: T;
  visitReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-doctors_select".
 */
export interface HospitalDoctorsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  designation?: T;
  speciality?: T;
  experience?: T;
  qualification?: T;
  image?: T;
  description?: T;
  languages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-specialities_select".
 */
export interface HospitalSpecialitiesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-testimonials_select".
 */
export interface HospitalTestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  patientName?: T;
  rating?: T;
  testimonial?: T;
  date?: T;
  treatment?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  image?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  publishedDate?: T;
  category?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}